defmodule AvatarDef do
  defstruct id: 0,
            account: "",
            platform: nil,
            login_url: "",
            name: "",
            server_ip: "",
            server_port: 0,
            conn: nil,
            token: "",
            claim: "",
            loop_ref: nil,
            ping_loop_ref: nil,
            buildings: %{},
            city_pos: nil,
            gid: 0,
            grids: %{},
            grids_limit: 10,
            heros: %{},
            points: %{},
            troops: %{},
            units: %{},
            fixed_units: %{},
            dynamic_units: %{},
            AI: false,
            system_mails: %{},
            group_mails: %{},
            login_finish: false,
            reconnect_times: 0,
            chat_data: %{},
            coll_report: %{}
end
